name: Gradle JAR Build

on:
  push:
    branches: [ "main", "fix/jar" ]
  pull_request:
    branches: [ "main", "fix/jar" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'
        java-package: 'jdk+fx'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build assemble
        build-root-directory: evosim
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: dist-${{ matrix.os }}
        path: evosim/build/distributions/*.zip
